---
- name: Install dependencies
  apt: pkg=unzip state=present

- name: Configure Tomcat instance
  copy: src=server.xml dest=/var/lib/tomcat7/conf/server.xml
  notify:
    - Restart Tomcat

- name: Remove ROOT webapp
  file: path=/var/lib/tomcat7/webapps/ROOT state=absent
  register: remove_tomcat_root
  notify:
    - Restart Tomcat

- name: Create Ice data directories
  file: path={{ item }} owner=tomcat7 group=tomcat7 mode=0777 state=directory
  with_items:
    - /mnt/ice_processor
    - /mnt/ice_reader

- name: Download Ice WAR
  get_url: url="{{ ice_war_url }}" dest=/var/lib/tomcat7/webapps/ice.war
  when: remove_tomcat_root|changed

- name: Create Ice deployment directory
  file: path=/var/lib/tomcat7/webapps/ice state=directory

- name: Decompress Ice WAR
  unarchive: src=/var/lib/tomcat7/webapps/ice.war
             dest=/var/lib/tomcat7/webapps/ice
             copy=no
  when: remove_tomcat_root|changed
  notify:
    - Restart Tomcat

- name: Remove Ice WAR
  file: path=/var/lib/tomcat7/webapps/ice.war state=absent
  notify:
    - Restart Tomcat

- name: Copy ice.properties
  template: src=ice.properties.j2 dest=/var/lib/tomcat7/webapps/ice/WEB-INF/classes/ice.properties
  notify:
    - Restart Tomcat
